2023-01-17 14:59:16,612 ERROR: Exception on / [GET] [in /Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/joannachen/Desktop/flask_proj/app/routes.py", line 31, in index
    return render_template('index.html',title = 'Home',form=form,posts=posts.items,next_url=next_url,prev_url=prev_url)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/joannachen/Desktop/flask_proj/app/templates/index.html", line 2, in top-level template code
    {%import 'bootstrap/wtf.html' as wtf%}
  File "/Users/joannachen/Desktop/flask_proj/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/joannachen/Desktop/flask_proj/app/templates/base.html", line 23, in block 'navbar'
    <li><a href="{{ url_for('user',user.username) }}">Profile</a></li>
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2023-01-17 15:00:09,494 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:49]
2023-01-17 15:00:10,455 ERROR: Exception on / [GET] [in /Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/joannachen/Desktop/flask_proj/app/routes.py", line 31, in index
    return render_template('index.html',title = 'Home',form=form,posts=posts.items,next_url=next_url,prev_url=prev_url)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/joannachen/Desktop/flask_proj/app/templates/index.html", line 2, in top-level template code
    {%import 'bootstrap/wtf.html' as wtf%}
  File "/Users/joannachen/Desktop/flask_proj/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/joannachen/Desktop/flask_proj/app/templates/base.html", line 23, in block 'navbar'
    <li><a href="{{ url_for('user',current_user.username) }}">Profile</a></li>
TypeError: Flask.url_for() takes 2 positional arguments but 3 were given
2023-01-17 15:00:43,141 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:49]
2023-01-17 15:03:03,786 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:49]
2023-01-17 15:03:09,586 ERROR: Exception on /user/susan [GET] [in /Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/joannachen/Desktop/flask_proj/app/routes.py", line 76, in user
    return render_template('user.html',user=user,posts=posts.items,form=form)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/joannachen/Desktop/flask_proj/app/templates/user.html", line 54, in template
    {%endblock%}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endif'. The innermost block that needs to be closed is 'if'.
2023-01-17 15:04:27,569 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:49]
