2023-01-17 21:43:49,359 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-17 21:45:18,705 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-17 21:50:26,158 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-17 21:52:12,472 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-17 21:52:20,102 ERROR: Exception on /user/susan [GET] [in /Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/joannachen/Desktop/flask_proj/app/routes.py", line 79, in user
    image_file = url_for('static',filename='profile_pics/' + user.image_file)
TypeError: can only concatenate str (not "NoneType") to str
2023-01-17 21:55:11,225 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-17 21:59:01,638 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-17 22:00:37,325 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-17 22:08:16,255 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-19 16:08:57,505 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-19 16:08:57,506 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-01-19 16:08:57,506 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-01-19 16:09:10,382 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-19 16:09:10,382 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-01-19 16:09:10,382 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-01-19 17:12:31,294 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-01-19 17:12:31,294 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-01-19 17:12:31,294 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-07-27 10:20:10,368 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-07-27 10:20:10,369 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-07-27 10:20:10,369 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-09-07 10:29:44,865 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:51]
2023-09-07 10:29:44,865 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-09-07 10:29:44,865 INFO: Microblog startup [in /Users/joannachen/Desktop/flask_proj/app/__init__.py:71]
2023-09-07 10:30:37,989 ERROR: Exception on /reset_password_request [POST] [in /Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 872, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/joannachen/Desktop/flask_proj/app/routes.py", line 182, in reset_password_request
    send_password_reset_email(user)
  File "/Users/joannachen/Desktop/flask_proj/app/email.py", line 14, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/Users/joannachen/Desktop/flask_proj/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/joannachen/Desktop/flask_proj/venv/lib/python3.10/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
